---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[build-essential::default]
      - recipe[git::default]
      - recipe[python::source]
      - recipe[postgresql::server]
      - recipe[security-monkey::default]
      - recipe[security-monkey::nginx]
    attributes:
      postgresql: 
        password:
          postgres: "changeme"
      security_monkey::
        mail_sender: 'david@severski.net'
        security_team_email: 'ciso.monitor@seattlechildrens.org'
        secret_key: 'a7ce90bb-fb1c-4ed5-82af-09dc3b980142'
        password_salt: '048c3eda-96f8-42a5-b0bb-bec191a632c0'
